### ISSUE TITLE
Remove Node_modules

### ISSUE THREAD

**Issue by qwo** [AnthonyShalagin/nodeschoolJavaScriptTutorials#1]
Issue:

Best practices in Node is to not commit our dependencies to source control.
we should commit `package.json` and `package-lock.json`. 

Solution:

Remove node_modules and add relevant dependencies to package json. Also add gitignore
https://github.com/github/gitignore/blob/master/Node.gitignore

@AnthonyShalagin

**Comment by AnthonyShalagin** [comment]
Done!
