### ISSUE TITLE
Consolidate all nodeschool workshop into their respective module.

### ISSUE THREAD

**Issue by qwo** [AnthonyShalagin/nodeschoolJavaScriptTutorials#2]
Problem
All the problem/solutions are top level and a tad disorganized

Solution
Make a folder and move the relevant exercises to the folder. It looks like these exercises are from "javascripting". Moving these to a mirror name of nodeschool modules is fine.

https://github.com/workshopper/javascripting

**Comment by AnthonyShalagin** [comment]
Done!
