### ISSUE TITLE
Clean Up Eslint Errors

### ISSUE THREAD

**Issue by qwo** [AnthonyShalagin/nodeschoolJavaScriptTutorials#4]
Issue 
![screen shot 2018-03-15 at 11 59 13 am](https://user-images.githubusercontent.com/3683993/37475126-565d284c-2848-11e8-840f-b095d303d159.png)

reproduce by installing eslint and typing `eslint`
Solution
Clean up the eslint issue outlined by eslint

**Comment by AnthonyShalagin** [comment]
Done!
